[package]
name = "spud"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
tokio = { version = "1.45.0", features = ["full"], optional = true }

[dev-dependencies]
tempfile = "3.20.0"

[features]
default = []

async = ["dep:tokio"]
